make[1]: Entering directory `/scratch/local/shzhu/EN_BOND/TEST/merra2_05x0625_tagCH4_as'
LAST BUILD INFORMATION:
  CODE_DIR     : ./CodeDir
  CODE_BRANCH  : GC_12.5.0
  LAST_COMMIT  : Add a feature request Github template 
  COMMIT_DATE  : Tue Sep 3 12:36:36 2019 -0400 
  VERSION      : 12.5.0
  VERSION_TAG  : GC_12.5.0
  MET          : merra2
  GRID         : 05x0625
  SIM          : tagCH4
  NEST         : as
  TRACEBACK    : y
  BOUNDS       : n
  DEBUG        : n
  FPE          : n
  NO_ISO       : n
  NO_REDUCED   : n
  CHEM         : 
  TOMAS12      : n
  TOMAS15      : n
  TOMAS30      : n
  TOMAS40      : n
  RRTMG        : n
  MASSCONS     : n
  TIMERS       : 0
  TAU_PROF     : n
  BPCH_DIAG    : y
  COMPILER     : gfortran 2015
  Datetime     : 2020/02/11 14:16	
make[1]: Leaving directory `/scratch/local/shzhu/EN_BOND/TEST/merra2_05x0625_tagCH4_as'
